### ISSUE TITLE
Failed installing gpg dependencies on EC2 Ubuntu instance

### ISSUE THREAD

**Issue by plotic** [christiangda/ansible-role-amazon-cloudwatch-agent#39]
Hey, I am trying to run this is script for ec2 instance  with 16.04.7 LTS 

`---
- hosts: all
  gather_facts: True
  become: true
  become_user: root
  become_method: sudo
  remote_user: user1
  roles:
  - role: christiangda.amazon_cloudwatch_agent 
`

But it is failing installing gpg 
TASK [christiangda.amazon_cloudwatch_agent : Install gpg dependencies on Debian Family] **********
FAILED - RETRYING: [X.X.X.X]: Install gpg dependencies on Debian Family (5 retries left).

Can you please advise. What i'm doing wrong. Thanks

**Comment by christiangda** [comment]
@plotic is your instance `arm64`?

**Comment by plotic** [comment]
hey @christiangda , no it is a x86_64

**Comment by gdd1984** [comment]
Hey @christiangda, having the same issue.

```
TASK [christiangda.amazon_cloudwatch_agent : Install gpg dependencies on Debian Family] ***
FAILED - RETRYING: [i-xxxxxxxxxxxxxxxxxxx]: Install gpg dependencies on Debian Family (5 retries left).
FAILED - RETRYING: [i-xxxxxxxxxxxxxxxxxxx]: Install gpg dependencies on Debian Family (4 retries left).
FAILED - RETRYING: [i-xxxxxxxxxxxxxxxxxxx]: Install gpg dependencies on Debian Family (3 retries left).
FAILED - RETRYING: [i-xxxxxxxxxxxxxxxxxxx]: Install gpg dependencies on Debian Family (2 retries left).
FAILED - RETRYING: [i-xxxxxxxxxxxxxxxxxxx]: Install gpg dependencies on Debian Family (1 retries left).
fatal: [i-xxxxxxxxxxxxxxxxxxx]: FAILED! => {"attempts": 5, "changed": false, "msg": "No package matching 'gpg' is available"}
```

The AWS instance type is as follows
```
# uname -a
Linux xxxxx.xxx.xxx 4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I did try a `apt update && apt upgrade`

Any clues as to what else we can do?

**Comment by christiangda** [comment]
fixed in PR #42

**Comment by gdd1984** [comment]
Hi @christiangda, thanks for pushing a fix through. However, I am still getting the same issue.

```
TASK [christiangda.amazon_cloudwatch_agent : Install gpg dependencies on Debian Family] *********************************************************************************************************************
FAILED - RETRYING: [i-xxxxxxxxxxxxxxxxxx3]: Install gpg dependencies on Debian Family (5 retries left).
FAILED - RETRYING: [i-xxxxxxxxxxxxxxxxxx3]: Install gpg dependencies on Debian Family (4 retries left).
FAILED - RETRYING: [i-xxxxxxxxxxxxxxxxxx3]: Install gpg dependencies on Debian Family (3 retries left).
FAILED - RETRYING: [i-xxxxxxxxxxxxxxxxxx3]: Install gpg dependencies on Debian Family (2 retries left).
FAILED - RETRYING: [i-xxxxxxxxxxxxxxxxxx3]: Install gpg dependencies on Debian Family (1 retries left).
fatal: [i-xxxxxxxxxxxxxxxxxx3]: FAILED! => {"attempts": 5, "changed": false, "msg": "No package matching 'gpg' is available"}
```

```
uname -a
Linux xxxxxxxxx 4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by christiangda** [comment]
Hi, @gdd1984 sorry to hear about that.

Are you sure you have the latest version of the role?

as you can see here (https://github.com/christiangda/ansible-role-amazon-cloudwatch-agent/blob/master/vars/ubuntu-16.yml) and after my change in the last version I install the package `gnupg` instead of  `gpg` for Ubuntu 16

**Comment by gdd1984** [comment]
You are correct @christiangda. Needed to specify `--force` flag to actually update the role. Also note there was a certificate issue which meant I had to add the `--ignore-certs` flag.

Thanks again for your help.
